name: Amplify Backend Deploy

on:
  push:
    branches:
      - dev

jobs:
  deploy-backend:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      # Step 1: Setup Node
      - name: Setup Node
        uses: actions/setup-node@v3
        with:
          node-version: 20

      # Step 2: Install Amplify CLI globally
      - name: Install Amplify CLI
        run: npm install -g @aws-amplify/backend-cli

      # Step 3: Deploy Amplify backend
      - name: Deploy Amplify backend
        run: npx ampx pipeline-deploy --branch dev --app-id d6c38s8spsb1t
        working-directory: .
