name: Amplify Backend Deploy

on:
  push:
    branches:
      - dev

jobs:
  deploy-backend:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      # Step 1: Setup Node
      - name: Setup Node
        uses: actions/setup-node@v3
        with:
          node-version: 20

      # Step 2: Install Amplify CLI globally
      - name: Install Amplify CLI
        run: npm install -g @aws-amplify/backend-cli

      # Step 3: Install Amplify backend dependencies
      - name: Install Amplify backend dependencies
        run: npm ci
        working-directory: ./amplify

      # Step 4: Configure AWS credentials
      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v2
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ca-central-1

      # Step 5: Deploy Amplify backend
      - name: Deploy Amplify backend
        run: npx ampx pipeline-deploy --branch ${{ github.ref_name }} --app-id d6c38s8spsb1t
        working-directory: ./amplify
