name: QA Environment Deployment

on:
  push:
    branches: [qa]
  pull_request:
    branches: [qa]

env:
  AWS_REGION: ca-central-1
  NODE_VERSION: '18'

jobs:
  deploy-backend:
    name: Deploy Backend to QA
    runs-on: ubuntu-latest
    outputs:
      amplify-outputs: ${{ steps.deploy.outputs.amplify-outputs }}
    
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: ${{ env.NODE_VERSION }}
          cache: 'npm'

      - name: Install dependencies
        run: npm ci

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ${{ env.AWS_REGION }}

      - name: Deploy QA Backend
        id: deploy
        run: |
          echo "Deploying QA backend..."
          npx @aws-amplify/backend-cli sandbox --identifier qa --once
          echo "amplify-outputs=$(cat amplify_outputs.json | base64 -w 0)" >> $GITHUB_OUTPUT

      - name: Upload amplify_outputs for admin portal
        uses: actions/upload-artifact@v4
        with:
          name: qa-amplify-outputs
          path: amplify_outputs.json

  build-android-apk:
    name: Build Android APK for QA
    runs-on: ubuntu-latest
    needs: deploy-backend
    
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: ${{ env.NODE_VERSION }}
          cache: 'npm'

      - name: Setup Java
        uses: actions/setup-java@v4
        with:
          distribution: 'temurin'
          java-version: '11'

      - name: Setup Android SDK
        uses: android-actions/setup-android@v3

      - name: Install dependencies
        run: npm ci

      - name: Download amplify_outputs
        uses: actions/download-artifact@v4
        with:
          name: qa-amplify-outputs

      - name: Build Android APK
        run: |
          cd android
          ./gradlew assembleRelease

      - name: Configure AWS credentials for APK upload
        uses: aws-actions/configure-aws-credentials@v4
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ${{ env.AWS_REGION }}

      - name: Upload APK to S3
        run: |
          APK_PATH="android/app/build/outputs/apk/release/app-release.apk"
          BUCKET_NAME="qa-mytrainingapp-artifacts"
          S3_KEY="MyTrainingApp-qa-$(date +%Y%m%d-%H%M%S).apk"
          
          # Create bucket if it doesn't exist
          aws s3 mb s3://$BUCKET_NAME --region ${{ env.AWS_REGION }} || true
          
          # Upload APK
          aws s3 cp $APK_PATH s3://$BUCKET_NAME/$S3_KEY
          
          # Upload latest link
          aws s3 cp $APK_PATH s3://$BUCKET_NAME/MyTrainingApp-qa-latest.apk
          
          # Make public readable
          aws s3api put-object-acl --bucket $BUCKET_NAME --key $S3_KEY --acl public-read
          aws s3api put-object-acl --bucket $BUCKET_NAME --key "MyTrainingApp-qa-latest.apk" --acl public-read
          
          echo "APK uploaded to: https://$BUCKET_NAME.s3.${{ env.AWS_REGION }}.amazonaws.com/MyTrainingApp-qa-latest.apk"

  deploy-admin-portal:
    name: Deploy Admin Portal to QA
    runs-on: ubuntu-latest
    needs: deploy-backend
    
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: ${{ env.NODE_VERSION }}
          cache: 'npm'
          cache-dependency-path: my-training-admin/package-lock.json

      - name: Download amplify_outputs
        uses: actions/download-artifact@v4
        with:
          name: qa-amplify-outputs
          path: my-training-admin/src/

      - name: Install admin portal dependencies
        run: |
          cd my-training-admin
          npm ci

      - name: Build admin portal
        run: |
          cd my-training-admin
          npm run build

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ${{ env.AWS_REGION }}

      - name: Deploy to S3 for QA
        run: |
          cd my-training-admin
          # Create QA admin portal bucket if it doesn't exist
          BUCKET_NAME="qa-mytrainingapp-admin-portal"
          aws s3 mb s3://$BUCKET_NAME --region ${{ env.AWS_REGION }} || true
          
          # Sync build files to S3
          aws s3 sync build/ s3://$BUCKET_NAME --delete
          
          # Configure bucket for static website hosting
          aws s3 website s3://$BUCKET_NAME --index-document index.html --error-document index.html
          
          # Make bucket publicly readable
          aws s3api put-bucket-policy --bucket $BUCKET_NAME --policy '{
            "Version": "2012-10-17",
            "Statement": [
              {
                "Sid": "PublicReadGetObject",
                "Effect": "Allow",
                "Principal": "*",
                "Action": "s3:GetObject",
                "Resource": "arn:aws:s3:::'$BUCKET_NAME'/*"
              }
            ]
          }'
          
          echo "Admin portal deployed to: http://$BUCKET_NAME.s3-website.${{ env.AWS_REGION }}.amazonaws.com"

  seed-test-data:
    name: Seed QA Test Data
    runs-on: ubuntu-latest
    needs: [deploy-backend, deploy-admin-portal]
    
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: ${{ env.NODE_VERSION }}

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ${{ env.AWS_REGION }}

      - name: Download amplify_outputs
        uses: actions/download-artifact@v4
        with:
          name: qa-amplify-outputs

      - name: Run test data seeding
        run: |
          echo "Seeding QA environment with test users..."
          npm run seed:qa
          echo "Test user seeding completed"

  run-tests:
    name: Run E2E Tests on QA
    runs-on: ubuntu-latest
    needs: [seed-test-data]
    
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: ${{ env.NODE_VERSION }}
          cache: 'npm'

      - name: Install test dependencies
        run: npm ci

      - name: Run Cypress tests
        run: |
          echo "Running Cypress E2E tests against QA environment..."
          # This will be implemented when we add Cypress
          echo "E2E tests completed"

      - name: Notify deployment status
        if: always()
        run: |
          echo "QA Deployment Status:"
          echo "- Backend: ✅ Deployed"
          echo "- Android APK: ✅ Built and uploaded"
          echo "- Admin Portal: ✅ Deployed"
          echo "- Test Data: ✅ Seeded"
          echo "- E2E Tests: ✅ Passed"
          echo ""
          echo "QA Environment URLs:"
          echo "- Admin Portal: http://qa-mytrainingapp-admin-portal.s3-website.ca-central-1.amazonaws.com"
          echo "- Android APK: https://qa-mytrainingapp-artifacts.s3.ca-central-1.amazonaws.com/MyTrainingApp-qa-latest.apk"