name: QA Environment Test

on:
  workflow_dispatch: # Allow manual trigger

env:
  AWS_REGION: ca-central-1
  NODE_VERSION: '18'

jobs:
  test-credentials:
    name: Test AWS Credentials
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ${{ env.AWS_REGION }}

      - name: Test AWS access
        run: |
          echo "Testing AWS credentials..."
          aws sts get-caller-identity
          echo "✅ AWS credentials working!"

  test-admin-build:
    name: Test Admin Portal Build
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: ${{ env.NODE_VERSION }}
          cache: 'npm'
          cache-dependency-path: my-training-admin/package-lock.json

      - name: Install dependencies
        run: |
          cd my-training-admin
          npm ci

      - name: Build admin portal
        run: |
          cd my-training-admin
          npm run build
          echo "✅ Admin portal build successful!"

  test-seeding:
    name: Test User Seeding
    runs-on: ubuntu-latest
    needs: test-credentials
    
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: ${{ env.NODE_VERSION }}
          cache: 'npm'

      - name: Install dependencies
        run: npm ci

      - name: Test seeding script syntax
        run: |
          echo "Testing seeding script..."
          node -c scripts/seed-qa-simple.js
          echo "✅ Seeding script syntax valid!"